name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mysql-database: webdb
          mysql root password: Charan@98
          mysql-character-set-server: 'utf8'
          mysql-collation-server: 'utf8_general_ci'
          mysql-port: 3306

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and Test
        run: |
          ./mvnw clean install
          ./mvnw test
