name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Set up MariaDB
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-server mariadb-client

      - name: Start and check MariaDB
        run: |
          sudo systemctl start mariadb
          sudo systemctl enable mariadb

      - name: Create User and Grant Access
        run: |
          sudo mysql -e "CREATE USER '${{ secrets.MARIADBUSERNAME}}'@'localhost' IDENTIFIED BY '${{ secrets.MARIADBPASSWORD}}';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${{ secrets.MARIADBUSERNAME}}'@'localhost' WITH GRANT OPTION;"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo systemctl status mariadb

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and Test
        run: |
          pwd
          ls -al
          chmod +x ./mvnw
          ./mvnw clean install
          ./mvnw test