name: ValidationTest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Validate Packer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Set up MariaDB
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-server mariadb-client

      - name: Start and check MariaDB
        run: |
          sudo systemctl start mariadb
          sudo systemctl enable mariadb
          sudo systemctl status mariadb

      - name: Create User and Grant Access
        run: |
          sudo mysql -e "CREATE USER '${{ secrets.MARIADBUSERNAME}}'@'${{ secrets.MARIADBHOST}}' IDENTIFIED BY '${{ secrets.MARIADBPASSWORD}}';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${{ secrets.MARIADBUSERNAME}}'@'${{ secrets.MARIADBHOST}}' WITH GRANT OPTION;"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Build with Maven
        env:
          DBHost: ${{ secrets.MARIADBHOST}}
          DBPort: ${{ secrets.MARIADBPORT}}
          DBDatabase: ${{ secrets.MARIADBDATABASE}}
          DBUser: ${{ secrets.MARIADBUSERNAME}}
          DBPassword: ${{ secrets.MARIADBPASSWORD}}
          AvailabilityZone: randomZone
          snsTopicArn: randomARN
          aws.region: randomRegion
        run: |
          mvn clean install
          pwd

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Initialize packer
        run: packer init ./packer/.

      - name: Format packer
        run: packer fmt ./packer/.

      - name: Check for Changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]; then
            echo "ERROR: Running 'packer fmt' made changes to the debian-ami.pkr.hcl file."
            exit 1
          fi

      - name: Validate packer
        run: packer validate ./packer/.