name: IntegrationTest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Validate Packer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup


      - name: Initialize packer
        run: packer init ./packer/.

      - name: Format packer
        run: packer fmt ./packer/.

      - name: Validate packer
        run: packer validate ./packer/.